#ifndef GAME_SERVER_CLASSES_H
#define GAME_SERVER_CLASSES_H

enum
{
	PLAYERCLASS_NONE = 0, // BRO!!!
	PLAYERCLASS_ASSASSIN = 2,
	PLAYERCLASS_BERSERK,
	PLAYERCLASS_HEALER,
	_ENDPLAYERCLASS,
	NUM_PLAYERCLASS = _ENDPLAYERCLASS - 2,
};

#endif
